# Generated by Django 2.0.1 on 2018-03-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='是否是超级用户'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='introduce_by',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='推荐由'),
        ),
    ]
