# Generated by Django 2.0.2 on 2018-04-16 02:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_emailvericode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='EmailVericode',
            name='send_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发送时间'),
        ),
    ]
