# Generated by Django 2.0.2 on 2018-06-10 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0005_auto_20180417_0923'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerifycode',
        ),
    ]
