# Generated by Django 2.0.2 on 2018-06-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0006_auto_20180614_1510'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerifycode',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='groups',
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='username',
            field=models.CharField(default='', max_length=24, verbose_name='用户名'),
        ),
    ]
