# Generated by Django 2.0.2 on 2018-06-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0006_delete_emailverifycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是否激活'),
        ),
    ]
