# Generated by Django 2.0.2 on 2018-08-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0007_auto_20180622_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='nickname',
            field=models.CharField(default='', max_length=24, verbose_name='真实姓名'),
        ),
    ]
