# Generated by Django 2.0.2 on 2018-06-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0008_auto_20180615_1046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerifycode',
        ),
        migrations.AlterField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是否激活'),
        ),
    ]
